// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_recipient_info(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::RecipientInfo,
) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.key_encryption_algorithm {
        object.key("KeyEncryptionAlgorithm").string(var_1.as_str());
    }
    if let Some(var_2) = &input.attestation_document {
        object
            .key("AttestationDocument")
            .string_unchecked(&::aws_smithy_types::base64::encode(var_2));
    }
    Ok(())
}
