FROM rust:alpine

RUN apk update ; apk add --no-cache --allow-untrusted ca-certificates curl bash git jq build-base linux-headers

ENV GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc
ENV GLIBC_VERSION=2.35-r0

RUN set -ex && \
    apk --update add libstdc++ curl ca-certificates && \
    for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION}; \
        do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done && \
    apk add --allow-untrusted /tmp/*.apk ; \
    rm -v /tmp/*.apk ;/usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib

# gcompat installs with an error but forge and cast need it to work.
# And it works regardless of the install error.
RUN apk add gcompat; echo "Sorry"

WORKDIR /usr/src/foundry
COPY . .

#RUN cd cli && cargo install --path .