/*
 * Compute Engine API
 *
 * Creates and runs virtual machines on Google Cloud Platform.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::google_rest_apis::compute_v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoscalersScopedList {
    /// [Output Only] A list of autoscalers contained in this scope.
    #[serde(rename = "autoscalers", skip_serializing_if = "Option::is_none")]
    pub autoscalers: Option<Vec<models::Autoscaler>>,
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<Box<models::AutoscalersScopedListWarning>>,
}

impl AutoscalersScopedList {
    pub fn new() -> AutoscalersScopedList {
        AutoscalersScopedList {
            autoscalers: None,
            warning: None,
        }
    }
}
