/*
 * Compute Engine API
 *
 * Creates and runs virtual machines on Google Cloud Platform.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::google_rest_apis::compute_v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkEndpointGroupsListEndpointsRequest {
    /// Optional query parameter for showing the health status of each network endpoint. Valid options are SKIP or SHOW. If you don't specify this parameter, the health status of network endpoints will not be provided.
    #[serde(rename = "healthStatus", skip_serializing_if = "Option::is_none")]
    pub health_status: Option<HealthStatus>,
}

impl NetworkEndpointGroupsListEndpointsRequest {
    pub fn new() -> NetworkEndpointGroupsListEndpointsRequest {
        NetworkEndpointGroupsListEndpointsRequest {
            health_status: None,
        }
    }
}
/// Optional query parameter for showing the health status of each network endpoint. Valid options are SKIP or SHOW. If you don't specify this parameter, the health status of network endpoints will not be provided.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthStatus {
    #[serde(rename = "SHOW")]
    Show,
    #[serde(rename = "SKIP")]
    Skip,
}

impl Default for HealthStatus {
    fn default() -> HealthStatus {
        Self::Show
    }
}
