/*
 * Compute Engine API
 *
 * Creates and runs virtual machines on Google Cloud Platform.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::google_rest_apis::compute_v1::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouterBgp {
    /// User-specified flag to indicate which mode to use for advertisement. The options are DEFAULT or CUSTOM.
    #[serde(rename = "advertiseMode", skip_serializing_if = "Option::is_none")]
    pub advertise_mode: Option<AdvertiseMode>,
    /// User-specified list of prefix groups to advertise in custom mode. This field can only be populated if advertise_mode is CUSTOM and is advertised to all peers of the router. These groups will be advertised in addition to any specified prefixes. Leave this field blank to advertise no custom groups.
    #[serde(rename = "advertisedGroups", skip_serializing_if = "Option::is_none")]
    pub advertised_groups: Option<Vec<AdvertisedGroups>>,
    /// User-specified list of individual IP ranges to advertise in custom mode. This field can only be populated if advertise_mode is CUSTOM and is advertised to all peers of the router. These IP ranges will be advertised in addition to any specified groups. Leave this field blank to advertise no custom IP ranges.
    #[serde(rename = "advertisedIpRanges", skip_serializing_if = "Option::is_none")]
    pub advertised_ip_ranges: Option<Vec<models::RouterAdvertisedIpRange>>,
    /// Local BGP Autonomous System Number (ASN). Must be an RFC6996 private ASN, either 16-bit or 32-bit. The value will be fixed for this router resource. All VPN tunnels that link to this router will have the same local ASN.
    #[serde(rename = "asn", skip_serializing_if = "Option::is_none")]
    pub asn: Option<i32>,
    /// The interval in seconds between BGP keepalive messages that are sent to the peer. Hold time is three times the interval at which keepalive messages are sent, and the hold time is the maximum number of seconds allowed to elapse between successive keepalive messages that BGP receives from a peer. BGP will use the smaller of either the local hold time value or the peer's hold time value as the hold time for the BGP connection between the two peers. If set, this value must be between 20 and 60. The default is 20.
    #[serde(rename = "keepaliveInterval", skip_serializing_if = "Option::is_none")]
    pub keepalive_interval: Option<i32>,
}

impl RouterBgp {
    pub fn new() -> RouterBgp {
        RouterBgp {
            advertise_mode: None,
            advertised_groups: None,
            advertised_ip_ranges: None,
            asn: None,
            keepalive_interval: None,
        }
    }
}
/// User-specified flag to indicate which mode to use for advertisement. The options are DEFAULT or CUSTOM.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdvertiseMode {
    #[serde(rename = "CUSTOM")]
    Custom,
    #[serde(rename = "DEFAULT")]
    Default,
}

impl Default for AdvertiseMode {
    fn default() -> AdvertiseMode {
        Self::Custom
    }
}
/// User-specified list of prefix groups to advertise in custom mode. This field can only be populated if advertise_mode is CUSTOM and is advertised to all peers of the router. These groups will be advertised in addition to any specified prefixes. Leave this field blank to advertise no custom groups.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdvertisedGroups {
    #[serde(rename = "ALL_SUBNETS")]
    AllSubnets,
}

impl Default for AdvertisedGroups {
    fn default() -> AdvertisedGroups {
        Self::AllSubnets
    }
}
