/// Maps an opcode and returns a vector of named affected indices
pub fn stack_indices_affected(op: u8) -> Vec<(usize, &'static str)> {
    match op {
        0x00 => vec![],
        0x01 => vec![(0, "a"), (1, "b")],
        0x02 => vec![(0, "a"), (1, "b")],
        0x03 => vec![(0, "a"), (1, "b")],
        0x04 => vec![(0, "a"), (1, "b")],
        0x05 => vec![(0, "a"), (1, "b")],
        0x06 => vec![(0, "a"), (1, "b")],
        0x07 => vec![(0, "a"), (1, "b")],
        0x08 => vec![(0, "a"), (1, "b"), (2, "N")],
        0x09 => vec![(0, "a"), (1, "b"), (2, "N")],
        0x0a => vec![(0, "a"), (1, "exponent")],
        0x0b => vec![(0, "b"), (1, "x")],
        0x0c => vec![],
        0x0d => vec![],
        0x0e => vec![],
        0x0f => vec![],
        0x10 => vec![(0, "a"), (1, "b")],
        0x11 => vec![(0, "a"), (1, "b")],
        0x12 => vec![(0, "a"), (1, "b")],
        0x13 => vec![(0, "a"), (1, "b")],
        0x14 => vec![(0, "a"), (1, "b")],
        0x15 => vec![(0, "a")],
        0x16 => vec![(0, "a"), (1, "b")],
        0x17 => vec![(0, "a"), (1, "b")],
        0x18 => vec![(0, "a"), (1, "b")],
        0x19 => vec![(0, "a")],
        0x1a => vec![(0, "i"), (1, "x")],
        0x1b => vec![(0, "shift"), (1, "value")],
        0x1c => vec![(0, "shift"), (1, "value")],
        0x1d => vec![(0, "shift"), (1, "value")],
        0x1e => vec![],
        0x1f => vec![],
        0x20 => vec![(0, "offset"), (1, "size")],
        0x21 => vec![],
        0x22 => vec![],
        0x23 => vec![],
        0x24 => vec![],
        0x25 => vec![],
        0x26 => vec![],
        0x27 => vec![],
        0x28 => vec![],
        0x29 => vec![],
        0x2a => vec![],
        0x2b => vec![],
        0x2c => vec![],
        0x2d => vec![],
        0x2e => vec![],
        0x2f => vec![],
        0x30 => vec![],
        0x31 => vec![(0, "address")],
        0x32 => vec![],
        0x33 => vec![],
        0x34 => vec![],
        0x35 => vec![(0, "offset")],
        0x36 => vec![],
        0x37 => vec![(0, "destOffset"), (1, "offset"), (2, "size")],
        0x38 => vec![],
        0x39 => vec![(0, "destOffset"), (1, "offset"), (2, "size")],
        0x3a => vec![],
        0x3b => vec![(0, "address")],
        0x3c => vec![(0, "address"), (1, "destOffset"), (2, "offset"), (3, "size")],
        0x3d => vec![],
        0x3e => vec![(0, "destOffset"), (1, "offset"), (2, "size")],
        0x3f => vec![(0, "address")],
        0x40 => vec![(0, "blockNumber")],
        0x41 => vec![],
        0x42 => vec![],
        0x43 => vec![],
        0x44 => vec![],
        0x45 => vec![],
        0x46 => vec![],
        0x47 => vec![],
        0x48 => vec![],
        0x49 => vec![],
        0x4a => vec![],
        0x4b => vec![],
        0x4c => vec![],
        0x4d => vec![],
        0x4e => vec![],
        0x4f => vec![],
        0x50 => vec![(0, "y")],
        0x51 => vec![(0, "offset")],
        0x52 => vec![(0, "offset"), (1, "value")],
        0x53 => vec![(0, "offset"), (1, "value")],
        0x54 => vec![(0, "key")],
        0x55 => vec![(0, "key"), (1, "value")],
        0x56 => vec![(0, "jump_to")],
        0x57 => vec![(0, "jump_to"), (1, "if")],
        0x58 => vec![],
        0x59 => vec![],
        0x5a => vec![],
        0x5b => vec![],
        0x5c => vec![],
        0x5d => vec![],
        0x5e => vec![],
        0x5f => vec![],
        0x60 => vec![],
        0x61 => vec![],
        0x62 => vec![],
        0x63 => vec![],
        0x64 => vec![],
        0x65 => vec![],
        0x66 => vec![],
        0x67 => vec![],
        0x68 => vec![],
        0x69 => vec![],
        0x6a => vec![],
        0x6b => vec![],
        0x6c => vec![],
        0x6d => vec![],
        0x6e => vec![],
        0x6f => vec![],
        0x70 => vec![],
        0x71 => vec![],
        0x72 => vec![],
        0x73 => vec![],
        0x74 => vec![],
        0x75 => vec![],
        0x76 => vec![],
        0x77 => vec![],
        0x78 => vec![],
        0x79 => vec![],
        0x7a => vec![],
        0x7b => vec![],
        0x7c => vec![],
        0x7d => vec![],
        0x7e => vec![],
        0x7f => vec![],
        0x80 => vec![(0, "dup_value")],
        0x81 => vec![(1, "dup_value")],
        0x82 => vec![(2, "dup_value")],
        0x83 => vec![(3, "dup_value")],
        0x84 => vec![(4, "dup_value")],
        0x85 => vec![(5, "dup_value")],
        0x86 => vec![(6, "dup_value")],
        0x87 => vec![(7, "dup_value")],
        0x88 => vec![(8, "dup_value")],
        0x89 => vec![(9, "dup_value")],
        0x8a => vec![(10, "dup_value")],
        0x8b => vec![(11, "dup_value")],
        0x8c => vec![(12, "dup_value")],
        0x8d => vec![(13, "dup_value")],
        0x8e => vec![(14, "dup_value")],
        0x8f => vec![(15, "dup_value")],
        0x90 => vec![(0, "a"), (1, "swap_value")],
        0x91 => vec![(0, "a"), (2, "swap_value")],
        0x92 => vec![(0, "a"), (3, "swap_value")],
        0x93 => vec![(0, "a"), (4, "swap_value")],
        0x94 => vec![(0, "a"), (5, "swap_value")],
        0x95 => vec![(0, "a"), (6, "swap_value")],
        0x96 => vec![(0, "a"), (7, "swap_value")],
        0x97 => vec![(0, "a"), (8, "swap_value")],
        0x98 => vec![(0, "a"), (9, "swap_value")],
        0x99 => vec![(0, "a"), (10, "swap_value")],
        0x9a => vec![(0, "a"), (11, "swap_value")],
        0x9b => vec![(0, "a"), (12, "swap_value")],
        0x9c => vec![(0, "a"), (13, "swap_value")],
        0x9d => vec![(0, "a"), (14, "swap_value")],
        0x9e => vec![(0, "a"), (15, "swap_value")],
        0x9f => vec![(0, "a"), (16, "swap_value")],
        0xa0 => vec![(0, "offset"), (1, "size")],
        0xa1 => vec![(0, "offset"), (1, "size"), (2, "topic")],
        0xa2 => vec![(0, "offset"), (1, "size"), (2, "topic1"), (3, "topic2")],
        0xa3 => vec![(0, "offset"), (1, "size"), (2, "topic1"), (3, "topic2"), (4, "topic3")],
        0xa4 => vec![
            (0, "offset"),
            (1, "size"),
            (2, "topic1"),
            (3, "topic2"),
            (4, "topic3"),
            (5, "topic4"),
        ],
        0xa5 => vec![],
        0xa6 => vec![],
        0xa7 => vec![],
        0xa8 => vec![],
        0xa9 => vec![],
        0xaa => vec![],
        0xab => vec![],
        0xac => vec![],
        0xad => vec![],
        0xae => vec![],
        0xaf => vec![],
        0xb0 => vec![],
        0xb1 => vec![],
        0xb2 => vec![],
        0xb3 => vec![],
        0xb4 => vec![],
        0xb5 => vec![],
        0xb6 => vec![],
        0xb7 => vec![],
        0xb8 => vec![],
        0xb9 => vec![],
        0xba => vec![],
        0xbb => vec![],
        0xbc => vec![],
        0xbd => vec![],
        0xbe => vec![],
        0xbf => vec![],
        0xc0 => vec![],
        0xc1 => vec![],
        0xc2 => vec![],
        0xc3 => vec![],
        0xc4 => vec![],
        0xc5 => vec![],
        0xc6 => vec![],
        0xc7 => vec![],
        0xc8 => vec![],
        0xc9 => vec![],
        0xca => vec![],
        0xcb => vec![],
        0xcc => vec![],
        0xcd => vec![],
        0xce => vec![],
        0xcf => vec![],
        0xd0 => vec![],
        0xd1 => vec![],
        0xd2 => vec![],
        0xd3 => vec![],
        0xd4 => vec![],
        0xd5 => vec![],
        0xd6 => vec![],
        0xd7 => vec![],
        0xd8 => vec![],
        0xd9 => vec![],
        0xda => vec![],
        0xdb => vec![],
        0xdc => vec![],
        0xdd => vec![],
        0xde => vec![],
        0xdf => vec![],
        0xe0 => vec![],
        0xe1 => vec![],
        0xe2 => vec![],
        0xe3 => vec![],
        0xe4 => vec![],
        0xe5 => vec![],
        0xe6 => vec![],
        0xe7 => vec![],
        0xe8 => vec![],
        0xe9 => vec![],
        0xea => vec![],
        0xeb => vec![],
        0xec => vec![],
        0xed => vec![],
        0xee => vec![],
        0xef => vec![],
        0xf0 => vec![(0, "value"), (1, "offset"), (2, "size")],
        0xf1 => vec![
            (0, "gas"),
            (1, "address"),
            (2, "value"),
            (3, "argsOffset"),
            (4, "argsSize"),
            (5, "retOffset"),
            (6, "retSize"),
        ],
        0xf2 => vec![
            (0, "gas"),
            (1, "address"),
            (2, "value"),
            (3, "argsOffset"),
            (4, "argsSize"),
            (5, "retOffset"),
            (6, "retSize"),
        ],
        0xf3 => vec![(0, "offset"), (1, "size")],
        0xf4 => vec![
            (0, "gas"),
            (1, "address"),
            (2, "argsOffset"),
            (3, "argsSize"),
            (4, "retOffset"),
            (5, "retSize"),
        ],
        0xf5 => vec![(0, "value"), (1, "offset"), (2, "size"), (3, "salt")],
        0xf6 => vec![],
        0xf7 => vec![],
        0xf8 => vec![],
        0xf9 => vec![],
        0xfa => vec![
            (0, "gas"),
            (1, "address"),
            (2, "argsOffset"),
            (3, "argsSize"),
            (4, "retOffset"),
            (5, "retSize"),
        ],
        0xfb => vec![],
        0xfc => vec![],
        0xfd => vec![(0, "offset"), (1, "size")],
        0xfe => vec![],
        0xff => vec![(0, "address")],
    }
}
