/// Maps an opcode to a list of named affected indices.
#[inline]
pub fn stack_indices_affected(op: u8) -> &'static [(usize, &'static str)] {
    OP_TO_EFFECT[op as usize]
}

static OP_TO_EFFECT: [&[(usize, &str)]; 256] = {
    let mut table = [[].as_slice(); 256];
    let mut i = 0;
    while i < 256 {
        table[i] = op_to_effect(i as u8);
        i += 1;
    }
    table
};

const fn op_to_effect(op: u8) -> &'static [(usize, &'static str)] {
    match op {
        0x01 => &[(0, "a"), (1, "b")],
        0x02 => &[(0, "a"), (1, "b")],
        0x03 => &[(0, "a"), (1, "b")],
        0x04 => &[(0, "a"), (1, "b")],
        0x05 => &[(0, "a"), (1, "b")],
        0x06 => &[(0, "a"), (1, "b")],
        0x07 => &[(0, "a"), (1, "b")],
        0x08 => &[(0, "a"), (1, "b"), (2, "N")],
        0x09 => &[(0, "a"), (1, "b"), (2, "N")],
        0x0a => &[(0, "a"), (1, "exponent")],
        0x0b => &[(0, "b"), (1, "x")],
        0x10 => &[(0, "a"), (1, "b")],
        0x11 => &[(0, "a"), (1, "b")],
        0x12 => &[(0, "a"), (1, "b")],
        0x13 => &[(0, "a"), (1, "b")],
        0x14 => &[(0, "a"), (1, "b")],
        0x15 => &[(0, "a")],
        0x16 => &[(0, "a"), (1, "b")],
        0x17 => &[(0, "a"), (1, "b")],
        0x18 => &[(0, "a"), (1, "b")],
        0x19 => &[(0, "a")],
        0x1a => &[(0, "i"), (1, "x")],
        0x1b => &[(0, "shift"), (1, "value")],
        0x1c => &[(0, "shift"), (1, "value")],
        0x1d => &[(0, "shift"), (1, "value")],
        0x20 => &[(0, "offset"), (1, "size")],
        0x31 => &[(0, "address")],
        0x35 => &[(0, "offset")],
        0x37 => &[(0, "destOffset"), (1, "offset"), (2, "size")],
        0x39 => &[(0, "destOffset"), (1, "offset"), (2, "size")],
        0x3b => &[(0, "address")],
        0x3c => &[(0, "address"), (1, "destOffset"), (2, "offset"), (3, "size")],
        0x3e => &[(0, "destOffset"), (1, "offset"), (2, "size")],
        0x3f => &[(0, "address")],
        0x40 => &[(0, "blockNumber")],
        0x50 => &[(0, "y")],
        0x51 => &[(0, "offset")],
        0x52 => &[(0, "offset"), (1, "value")],
        0x53 => &[(0, "offset"), (1, "value")],
        0x54 => &[(0, "key")],
        0x55 => &[(0, "key"), (1, "value")],
        0x56 => &[(0, "jump_to")],
        0x57 => &[(0, "jump_to"), (1, "if")],
        0x5c => &[(0, "key")],
        0x5d => &[(0, "key"), (1, "value")],
        0x80 => &[(0, "dup_value")],
        0x81 => &[(1, "dup_value")],
        0x82 => &[(2, "dup_value")],
        0x83 => &[(3, "dup_value")],
        0x84 => &[(4, "dup_value")],
        0x85 => &[(5, "dup_value")],
        0x86 => &[(6, "dup_value")],
        0x87 => &[(7, "dup_value")],
        0x88 => &[(8, "dup_value")],
        0x89 => &[(9, "dup_value")],
        0x8a => &[(10, "dup_value")],
        0x8b => &[(11, "dup_value")],
        0x8c => &[(12, "dup_value")],
        0x8d => &[(13, "dup_value")],
        0x8e => &[(14, "dup_value")],
        0x8f => &[(15, "dup_value")],
        0x90 => &[(0, "a"), (1, "swap_value")],
        0x91 => &[(0, "a"), (2, "swap_value")],
        0x92 => &[(0, "a"), (3, "swap_value")],
        0x93 => &[(0, "a"), (4, "swap_value")],
        0x94 => &[(0, "a"), (5, "swap_value")],
        0x95 => &[(0, "a"), (6, "swap_value")],
        0x96 => &[(0, "a"), (7, "swap_value")],
        0x97 => &[(0, "a"), (8, "swap_value")],
        0x98 => &[(0, "a"), (9, "swap_value")],
        0x99 => &[(0, "a"), (10, "swap_value")],
        0x9a => &[(0, "a"), (11, "swap_value")],
        0x9b => &[(0, "a"), (12, "swap_value")],
        0x9c => &[(0, "a"), (13, "swap_value")],
        0x9d => &[(0, "a"), (14, "swap_value")],
        0x9e => &[(0, "a"), (15, "swap_value")],
        0x9f => &[(0, "a"), (16, "swap_value")],
        0xa0 => &[(0, "offset"), (1, "size")],
        0xa1 => &[(0, "offset"), (1, "size"), (2, "topic")],
        0xa2 => &[(0, "offset"), (1, "size"), (2, "topic1"), (3, "topic2")],
        0xa3 => &[(0, "offset"), (1, "size"), (2, "topic1"), (3, "topic2"), (4, "topic3")],
        0xa4 => &[
            (0, "offset"),
            (1, "size"),
            (2, "topic1"),
            (3, "topic2"),
            (4, "topic3"),
            (5, "topic4"),
        ],
        0xf0 => &[(0, "value"), (1, "offset"), (2, "size")],
        0xf1 => &[
            (0, "gas"),
            (1, "address"),
            (2, "value"),
            (3, "argsOffset"),
            (4, "argsSize"),
            (5, "retOffset"),
            (6, "retSize"),
        ],
        0xf2 => &[
            (0, "gas"),
            (1, "address"),
            (2, "value"),
            (3, "argsOffset"),
            (4, "argsSize"),
            (5, "retOffset"),
            (6, "retSize"),
        ],
        0xf3 => &[(0, "offset"), (1, "size")],
        0xf4 => &[
            (0, "gas"),
            (1, "address"),
            (2, "argsOffset"),
            (3, "argsSize"),
            (4, "retOffset"),
            (5, "retSize"),
        ],
        0xf5 => &[(0, "value"), (1, "offset"), (2, "size"), (3, "salt")],
        0xfa => &[
            (0, "gas"),
            (1, "address"),
            (2, "argsOffset"),
            (3, "argsSize"),
            (4, "retOffset"),
            (5, "retSize"),
        ],
        0xfd => &[(0, "offset"), (1, "size")],
        0xff => &[(0, "address")],
        _ => &[],
    }
}
