[package]
name = "foundry-primitives"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types = { workspace = true, features = ["trace"] }
alloy-rpc-types-eth.workspace = true
alloy-serde.workspace = true
alloy-signer.workspace = true
alloy-evm.workspace = true
op-alloy-consensus = { workspace = true, features = ["serde", "alloy-compat"], optional = true }
op-alloy-rpc-types = { workspace = true, optional = true }
alloy-op-evm = { workspace = true, optional = true }
op-revm = { workspace = true, optional = true }

# Base
base-common-consensus = { workspace = true, optional = true, features = [
    "alloy-compat",
    "evm",
    "k256",
    "serde",
    "std",
] }
base-common-evm = { workspace = true, optional = true, features = [
    "blst",
    "c-kzg",
    "memory_limit",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_no_base_fee",
    "serde",
    "std",
] }
base-common-rpc-types = { workspace = true, optional = true, features = ["serde", "std"] }

revm.workspace = true
serde_json.workspace = true
serde = { version = "1.0", features = ["derive"] }
derive_more.workspace = true
tempo-primitives.workspace = true
tempo-alloy.workspace = true
tempo-revm.workspace = true

[features]
default = ["optimism"]
base = [
    "dep:base-common-consensus",
    "dep:base-common-evm",
    "dep:base-common-rpc-types",
    "dep:op-alloy-consensus",
    "dep:op-revm",
]
optimism = [
    "dep:op-alloy-consensus",
    "dep:op-alloy-rpc-types",
    "dep:alloy-op-evm",
    "dep:op-revm",
]
