// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteAliasOutput {
    _request_id: Option<String>,
}
impl ::aws_types::request_id::RequestId for DeleteAliasOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl DeleteAliasOutput {
    /// Creates a new builder-style object to manufacture [`DeleteAliasOutput`](crate::operation::delete_alias::DeleteAliasOutput).
    pub fn builder() -> crate::operation::delete_alias::builders::DeleteAliasOutputBuilder {
        crate::operation::delete_alias::builders::DeleteAliasOutputBuilder::default()
    }
}

/// A builder for [`DeleteAliasOutput`](crate::operation::delete_alias::DeleteAliasOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteAliasOutputBuilder {
    _request_id: Option<String>,
}
impl DeleteAliasOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteAliasOutput`](crate::operation::delete_alias::DeleteAliasOutput).
    pub fn build(self) -> crate::operation::delete_alias::DeleteAliasOutput {
        crate::operation::delete_alias::DeleteAliasOutput {
            _request_id: self._request_id,
        }
    }
}
