/*
 * BigQuery API
 *
 * A data platform for customers to create, manage, share and query data.
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::google_rest_apis::bigquery_v2::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BigQueryModelTraining {
    /// [Output-only, Beta] Index of current ML training iteration. Updated during create model query job to show job progress.
    #[serde(rename = "currentIteration", skip_serializing_if = "Option::is_none")]
    pub current_iteration: Option<i32>,
    /// [Output-only, Beta] Expected number of iterations for the create model query job specified as num_iterations in the input query. The actual total number of iterations may be less than this number due to early stop.
    #[serde(
        rename = "expectedTotalIterations",
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_total_iterations: Option<String>,
}

impl BigQueryModelTraining {
    pub fn new() -> BigQueryModelTraining {
        BigQueryModelTraining {
            current_iteration: None,
            expected_total_iterations: None,
        }
    }
}
