//! Configuration for `forge coverage`.

use clap::ValueEnum;
use semver::Version;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Coverage report kinds that can be generated by `forge coverage`.
///
/// Used both as a CLI value (`--report <kind>`) and as a TOML configuration
/// value under `[profile.<name>.coverage] report = ["..."]`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize, ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum CoverageReportKind {
    #[default]
    Summary,
    Lcov,
    Debug,
    Bytecode,
}

/// Configuration for `forge coverage`, exposed under `[coverage]` and
/// `[profile.<name>.coverage]` in `foundry.toml`.
///
/// Fields here mirror the CLI flags accepted by `forge coverage`. CLI flags
/// take precedence over configuration values when both are provided.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CoverageConfig {
    /// The report kinds to generate. Defaults to `["summary"]`.
    #[serde(default = "default_report_kinds")]
    pub report: Vec<CoverageReportKind>,

    /// The version of the LCOV "tracefile" format to use.
    ///
    /// Defaults to `1` (parsed as `1.0.0`). See `forge coverage --help` for the
    /// supported variants and their differences.
    #[serde(default = "default_lcov_version")]
    pub lcov_version: Version,

    /// Whether to enable `viaIR` with minimum optimization. Useful as a
    /// workaround for "stack too deep" errors at the cost of source map
    /// accuracy.
    #[serde(default)]
    pub ir_minimum: bool,

    /// Path to write the coverage report to (relative to the project root). If
    /// unset, the report is written to the project root.
    #[serde(default)]
    pub report_file: Option<PathBuf>,

    /// Whether to include library dependencies in the coverage report.
    #[serde(default)]
    pub include_libs: bool,

    /// Whether to exclude tests from the coverage report.
    #[serde(default)]
    pub exclude_tests: bool,

    /// Glob patterns of source files to exclude from the coverage report.
    ///
    /// Patterns are matched against project-root-relative paths using the
    /// `globset` crate's `Glob` semantics (`**`, `*`, `?`, character classes).
    /// A file is skipped if any pattern matches.
    ///
    /// Example:
    /// ```toml
    /// [profile.default.coverage]
    /// skip_files = ["test/**", "script/**", "src/mocks/**"]
    /// ```
    #[serde(default)]
    pub skip_files: Vec<String>,
}

impl Default for CoverageConfig {
    fn default() -> Self {
        Self {
            report: default_report_kinds(),
            lcov_version: default_lcov_version(),
            ir_minimum: false,
            report_file: None,
            include_libs: false,
            exclude_tests: false,
            skip_files: Vec::new(),
        }
    }
}

fn default_report_kinds() -> Vec<CoverageReportKind> {
    vec![CoverageReportKind::Summary]
}

const fn default_lcov_version() -> Version {
    Version::new(1, 0, 0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_matches_cli_defaults() {
        let cfg = CoverageConfig::default();
        assert_eq!(cfg.report, vec![CoverageReportKind::Summary]);
        assert_eq!(cfg.lcov_version, Version::new(1, 0, 0));
        assert!(!cfg.ir_minimum);
        assert!(cfg.report_file.is_none());
        assert!(!cfg.include_libs);
        assert!(!cfg.exclude_tests);
        assert!(cfg.skip_files.is_empty());
    }

    #[test]
    fn deserialize_from_toml() {
        let toml = r#"
            report = ["summary", "lcov"]
            lcov_version = "2.2.0"
            ir_minimum = true
            report_file = "out/lcov.info"
            include_libs = true
            exclude_tests = true
            skip_files = ["test/**", "src/mocks/**"]
        "#;
        let cfg: CoverageConfig = toml::from_str(toml).unwrap();
        assert_eq!(cfg.report, vec![CoverageReportKind::Summary, CoverageReportKind::Lcov]);
        assert_eq!(cfg.lcov_version, Version::new(2, 2, 0));
        assert!(cfg.ir_minimum);
        assert_eq!(cfg.report_file.as_deref(), Some(std::path::Path::new("out/lcov.info")));
        assert!(cfg.include_libs);
        assert!(cfg.exclude_tests);
        assert_eq!(cfg.skip_files, vec!["test/**".to_string(), "src/mocks/**".to_string()]);
    }

    #[test]
    fn deserialize_partial_uses_defaults() {
        let toml = r#"skip_files = ["src/mocks/**"]"#;
        let cfg: CoverageConfig = toml::from_str(toml).unwrap();
        // Defaulted fields keep their default values.
        assert_eq!(cfg.report, vec![CoverageReportKind::Summary]);
        assert_eq!(cfg.lcov_version, Version::new(1, 0, 0));
        assert!(!cfg.ir_minimum);
        // Set field came through.
        assert_eq!(cfg.skip_files, vec!["src/mocks/**".to_string()]);
    }
}
