/*
 * Cloud Storage JSON API
 *
 * Stores and retrieves potentially large, immutable data objects.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::google_rest_apis::storage_v1::models;
use serde::{Deserialize, Serialize};

/// BucketObjectRetention : The bucket's object retention config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketObjectRetention {
    /// The bucket's object retention mode. Can be Enabled.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
}

impl BucketObjectRetention {
    /// The bucket's object retention config.
    pub fn new() -> BucketObjectRetention {
        BucketObjectRetention { mode: None }
    }
}
