// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DisableKeyOutput {
    _request_id: Option<String>,
}
impl ::aws_types::request_id::RequestId for DisableKeyOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl DisableKeyOutput {
    /// Creates a new builder-style object to manufacture [`DisableKeyOutput`](crate::operation::disable_key::DisableKeyOutput).
    pub fn builder() -> crate::operation::disable_key::builders::DisableKeyOutputBuilder {
        crate::operation::disable_key::builders::DisableKeyOutputBuilder::default()
    }
}

/// A builder for [`DisableKeyOutput`](crate::operation::disable_key::DisableKeyOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DisableKeyOutputBuilder {
    _request_id: Option<String>,
}
impl DisableKeyOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DisableKeyOutput`](crate::operation::disable_key::DisableKeyOutput).
    pub fn build(self) -> crate::operation::disable_key::DisableKeyOutput {
        crate::operation::disable_key::DisableKeyOutput {
            _request_id: self._request_id,
        }
    }
}
