# Reusable workflow for running tests via `cargo nextest`

name: test

permissions: {}

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
    secrets:
      ETHERSCAN_API_KEY:
        required: false
      ARBITRUM_RPC:
        required: false
      ETH_SEPOLIA_RPC:
        required: false

concurrency:
  group: tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"
  RUST_MIN_STACK: 4194304 # 2 * the default (2 * 1024 * 1024)

jobs:
  matrices:
    name: build matrices
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      test-matrix: ${{ steps.gen.outputs.test-matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Generate matrices
        id: gen
        env:
          EVENT_NAME: ${{ github.event_name }}
          PROFILE: ${{ inputs.profile }}
        shell: bash
        run: |
          output=$(python3 .github/scripts/matrices.py)
          printf '::debug::test-matrix=%s\n' "$output"
          printf 'test-matrix=%s\n' "$output" >> "$GITHUB_OUTPUT"

  test:
    name: test ${{ matrix.name }}
    runs-on: ${{ matrix.runner_label }}
    timeout-minutes: 60
    permissions:
      contents: read
    needs: matrices
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrices.outputs.test-matrix) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - uses: taiki-e/install-action@5f57d6cb7cd20b14a8a27f522884c4bc8a187458 # v2.75.19
        with:
          tool: nextest

      # External tests dependencies
      - name: Setup Node.js
        if: contains(matrix.name, 'external')
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install Bun
        if: contains(matrix.name, 'external')
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Install Vyper
        # Also update vyper version in .devcontainer/Dockerfile.dev
        run: pip --version && pip install vyper==0.4.3

      - name: Foundry test cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.foundry/cache
            ~/.config/.foundry/cache
            testdata/cache
            testdata/out
          # Use a unique key for each run to always update the cache.
          key: ${{ runner.os }}-foundry-${{ matrix.name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-foundry-${{ matrix.name }}-
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --global url."https://github.com/".insteadOf "git@github.com:"
      - name: Test
        env:
          SVM_TARGET_PLATFORM: ${{ matrix.svm_target_platform }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
          ETH_SEPOLIA_RPC: ${{ secrets.ETH_SEPOLIA_RPC }}
        run: cargo nextest run --locked ${{ matrix.flags }}
